import datetime
from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text, Index, UniqueConstraint
from sqlalchemy.orm import relationship as orm_relationship
from .database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    is_admin = Column(Boolean, default=False)
    nickname = Column(String, nullable=True)

    
    # Camouflage Nine-Palace pattern lock sequence.
    # Default sequence: "1,2,3" represents T-Rex (1) -> Triceratops (2) -> Pterodactyl (3)
    lock_pattern = Column(String, default="1,2,3")
    
    # Flags: "none", "default_requested"
    lock_reset_flag = Column(String, default="none")
    theme = Column(String, default="dark-neon")
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    
    # Cloud sync assets for sticker gameplay
    sticker_inventory = Column(String, default="", nullable=False)
    canvas_inventory = Column(String, default="3001", nullable=False) # 存储已解锁/购买的画布套 ID，如 "3001,3002"
    egg_energy = Column(Integer, default=100, nullable=False)

    # Relationships
    logs = orm_relationship("Log", back_populates="user", cascade="all, delete-orphan")

from sqlalchemy import Table

class DinoConfig(Base):
    __tablename__ = "dino_config"

    id = Column(Integer, primary_key=True, index=True)
    legacy_key = Column(String, unique=True, nullable=False)
    name = Column(String, nullable=False)
    mood_label = Column(String, nullable=False)
    mood_tip = Column(String, nullable=True)
    image_url = Column(String, nullable=False)
    mood_score = Column(Integer, nullable=False, default=5)
    sort_order = Column(Integer, nullable=False, default=99)
    is_active = Column(Boolean, nullable=False, default=True)

# Association table for multi-person relationships with logs
log_person_association = Table(
    "log_person_association",
    Base.metadata,
    Column("log_uuid", String, ForeignKey("logs.uuid", ondelete="CASCADE"), primary_key=True),
    Column("person_uuid", String, ForeignKey("persons.uuid", ondelete="CASCADE"), primary_key=True, index=True)
)

class Log(Base):
    __tablename__ = "logs"

    __table_args__ = (
        Index("idx_logs_user_deleted_incident", "user_id", "is_deleted", "incident_date"),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # UUID generated by client for offline-first syncing
    uuid = Column(String, unique=True, index=True, nullable=False)
    title = Column(String, nullable=True)
    
    incident_date = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)
    
    # Mood dinosaur foreign key
    mood_dino_id = Column(Integer, ForeignKey("dino_config.id", ondelete="RESTRICT"), nullable=False)
    
    # Description of what happened
    content = Column(Text, nullable=False)
    
    # My thoughts & reflection (now acting as private thoughts / secret words)
    own_thoughts = Column(Text, nullable=True)
    
    is_deleted = Column(Boolean, default=False)
    version = Column(Integer, default=1, nullable=False)

    # Relationships
    user = orm_relationship("User", back_populates="logs")
    dino_config = orm_relationship("DinoConfig")
    attachments = orm_relationship("Attachment", back_populates="log", cascade="all, delete-orphan")
    persons = orm_relationship("Person", secondary=log_person_association, back_populates="logs")

    @property
    def person_uuids(self):
        return [p.uuid for p in self.persons]

class PersonCategory(Base):
    __tablename__ = "person_categories"

    __table_args__ = (
        Index("idx_categories_user_deleted", "user_id", "is_deleted"),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    uuid = Column(String, unique=True, index=True, nullable=False)
    
    name = Column(String, nullable=False)
    sort_order = Column(Integer, default=0, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

    # Relationships
    user = orm_relationship("User", backref="person_categories")

class Person(Base):
    __tablename__ = "persons"

    __table_args__ = (
        Index("idx_persons_user_deleted", "user_id", "is_deleted"),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    uuid = Column(String, unique=True, index=True, nullable=False)
    
    name = Column(String, nullable=False)
    abbreviation = Column(String, nullable=False) # XM etc.
    relationship = Column(String, nullable=False) # Father, Mother, classmate, etc.
    
    category_uuid = Column(String, ForeignKey("person_categories.uuid", ondelete="SET NULL"), nullable=True)
    sort_order = Column(Integer, default=0, nullable=False)
    color_tag = Column(String, default="red", nullable=True)
    is_temporary = Column(Boolean, default=False, nullable=False)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

    # Relationships
    user = orm_relationship("User", backref="persons")
    logs = orm_relationship("Log", secondary=log_person_association, back_populates="persons")
    category = orm_relationship("PersonCategory", backref="persons")

class Attachment(Base):
    __tablename__ = "attachments"

    id = Column(Integer, primary_key=True, index=True)
    log_id = Column(Integer, ForeignKey("logs.id", ondelete="CASCADE"), nullable=True, index=True)
    log_uuid = Column(String, nullable=True, index=True)
    
    # Client-generated file UUID
    uuid = Column(String, unique=True, index=True, nullable=False)
    
    file_path = Column(String, nullable=False)
    file_name = Column(String, nullable=False)
    mime_type = Column(String, nullable=False)
    file_size = Column(Integer, nullable=False)
    md5 = Column(String, index=True, nullable=True)
    title = Column(String, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    log = orm_relationship("Log", back_populates="attachments")

class StickerSeries(Base):
    __tablename__ = "sticker_series"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    sort_order = Column(Integer, nullable=False, default=0)
    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_deleted = Column(Boolean, nullable=False, default=False)

class StickerConfig(Base):
    __tablename__ = "sticker_configs"

    id = Column(Integer, primary_key=True, index=True)
    series_id = Column(Integer, ForeignKey("sticker_series.id", ondelete="SET NULL"), nullable=True)
    name = Column(String, nullable=False)
    image_url = Column(String, nullable=False)
    description = Column(String, nullable=True)
    sort_order = Column(Integer, nullable=False, default=0)
    exchange_price = Column(Integer, nullable=False, default=20)
    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    is_deleted = Column(Boolean, nullable=False, default=False)


class CanvasSeries(Base):
    """
    画布系列表：对背景画布套进行大分类
    """
    __tablename__ = "canvas_series"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    sort_order = Column(Integer, nullable=False, default=0)  # 系列间的显示排序
    is_active = Column(Boolean, nullable=False, default=True)  # 启用状态
    is_deleted = Column(Boolean, nullable=False, default=False)  # 软删除
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)


class CanvasSet(Base):
    """
    画布套/商品表：商城的兑换单元（如 3001 '侏罗纪森林'）
    """
    __tablename__ = "canvas_sets"

    id = Column(Integer, primary_key=True, index=True)  # 自增主键，从 3001 起步
    series_id = Column(Integer, ForeignKey("canvas_series.id", ondelete="SET NULL"), nullable=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=True)
    sort_order = Column(Integer, nullable=False, default=0)  # 同系列内的展示排序
    exchange_price = Column(Integer, nullable=False, default=50)  # 兑换所需蛋能量
    is_active = Column(Boolean, nullable=False, default=True)
    is_deleted = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)


class CanvasInstance(Base):
    """
    画布图片实例表：保存特定比例画布裁剪后物理图片的真实信息
    """
    __tablename__ = "canvas_instances"

    id = Column(Integer, primary_key=True, index=True)  # 自增主键，从 4001 起步
    canvas_set_id = Column(Integer, ForeignKey("canvas_sets.id", ondelete="CASCADE"), nullable=False)
    aspect_ratio = Column(String, nullable=False)  # 枚举："16:9", "4:3", "1:1", "2:1"
    image_url = Column(String, nullable=False)  # 静态图片路径
    width = Column(Integer, nullable=False, default=1440)
    height = Column(Integer, nullable=False)  # 基于宽高比计算的高度
    is_active = Column(Boolean, nullable=False, default=True)
    is_deleted = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    # 联合唯一性约束，防止同套画布下重复上传相同比例的图片
    __table_args__ = (
        UniqueConstraint("canvas_set_id", "aspect_ratio", name="uq_canvas_set_ratio"),
    )


class LogCanvas(Base):
    """
    日记画布关联表：维护日记与特定背景画布实例的关系
    """
    __tablename__ = "log_canvases"

    log_uuid = Column(String, ForeignKey("logs.uuid", ondelete="CASCADE"), primary_key=True)
    canvas_instance_id = Column(Integer, ForeignKey("canvas_instances.id", ondelete="SET NULL"), nullable=True)
    canvas_aspect_ratio = Column(String, nullable=False, default="2:1")  # "16:9", "4:3", "1:1", "2:1"




