import datetime
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Float, ForeignKey, Text, Index, UniqueConstraint
from sqlalchemy.orm import relationship as orm_relationship
from .database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    is_admin = Column(Boolean, default=False)
    nickname = Column(String, nullable=True)

    
    # Camouflage Nine-Palace pattern lock sequence.
    # Default sequence: "1,2,3" represents T-Rex (1) -> Triceratops (2) -> Pterodactyl (3)
    lock_pattern = Column(String, default="1,2,3")
    
    # Flags: "none", "default_requested"
    lock_reset_flag = Column(String, default="none")
    theme = Column(String, default="dark-neon")
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    
    # Cloud sync assets for sticker gameplay
    sticker_inventory = Column(String, default="", nullable=False)
    canvas_inventory = Column(String, default="3001", nullable=False) # 存储已解锁/购买的画布套 ID，如 "3001,3002"
    egg_energy = Column(Integer, default=100, nullable=False)

    # Relationships
    logs = orm_relationship("Log", back_populates="user", cascade="all, delete-orphan")

from sqlalchemy import Table

class DinoConfig(Base):
    __tablename__ = "dino_config"

    id = Column(Integer, primary_key=True, index=True)
    legacy_key = Column(String, unique=True, nullable=False)
    name = Column(String, nullable=False)
    mood_label = Column(String, nullable=False)
    mood_tip = Column(String, nullable=True)
    image_url = Column(String, nullable=False)
    mood_score = Column(Integer, nullable=False, default=5)
    sort_order = Column(Integer, nullable=False, default=99)
    is_active = Column(Boolean, nullable=False, default=True)

# Association table for multi-person relationships with logs
log_person_association = Table(
    "log_person_association",
    Base.metadata,
    Column("log_uuid", String, ForeignKey("logs.uuid", ondelete="CASCADE"), primary_key=True),
    Column("person_uuid", String, ForeignKey("persons.uuid", ondelete="CASCADE"), primary_key=True, index=True)
)

class Log(Base):
    __tablename__ = "logs"

    __table_args__ = (
        Index("idx_logs_user_deleted_incident", "user_id", "is_deleted", "incident_date"),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # UUID generated by client for offline-first syncing
    uuid = Column(String, unique=True, index=True, nullable=False)
    title = Column(String, nullable=True)
    
    incident_date = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)
    
    # Mood dinosaur foreign key
    mood_dino_id = Column(Integer, ForeignKey("dino_config.id", ondelete="RESTRICT"), nullable=False)
    
    # Description of what happened
    content = Column(Text, nullable=False)
    
    # My thoughts & reflection (now acting as private thoughts / secret words)
    own_thoughts = Column(Text, nullable=True)
    
    is_deleted = Column(Boolean, default=False)
    version = Column(Integer, default=1, nullable=False)
    media_rewarded = Column(Boolean, default=False, nullable=False)


    # Relationships
    user = orm_relationship("User", back_populates="logs")
    dino_config = orm_relationship("DinoConfig")
    attachments = orm_relationship("Attachment", back_populates="log", cascade="all, delete-orphan")
    persons = orm_relationship("Person", secondary=log_person_association, back_populates="logs")

    @property
    def person_uuids(self):
        return [p.uuid for p in self.persons]

class PersonCategory(Base):
    __tablename__ = "person_categories"

    __table_args__ = (
        Index("idx_categories_user_deleted", "user_id", "is_deleted"),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    uuid = Column(String, unique=True, index=True, nullable=False)
    
    name = Column(String, nullable=False)
    sort_order = Column(Integer, default=0, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

    # Relationships
    user = orm_relationship("User", backref="person_categories")

class Person(Base):
    __tablename__ = "persons"

    __table_args__ = (
        Index("idx_persons_user_deleted", "user_id", "is_deleted"),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    uuid = Column(String, unique=True, index=True, nullable=False)
    
    name = Column(String, nullable=False)
    abbreviation = Column(String, nullable=False) # XM etc.
    relationship = Column(String, nullable=False) # Father, Mother, classmate, etc.
    
    category_uuid = Column(String, ForeignKey("person_categories.uuid", ondelete="SET NULL"), nullable=True)
    sort_order = Column(Integer, default=0, nullable=False)
    color_tag = Column(String, default="red", nullable=True)
    is_temporary = Column(Boolean, default=False, nullable=False)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

    # Relationships
    user = orm_relationship("User", backref="persons")
    logs = orm_relationship("Log", secondary=log_person_association, back_populates="persons")
    category = orm_relationship("PersonCategory", backref="persons")

class Attachment(Base):
    __tablename__ = "attachments"

    id = Column(Integer, primary_key=True, index=True)
    log_id = Column(Integer, ForeignKey("logs.id", ondelete="CASCADE"), nullable=True, index=True)
    log_uuid = Column(String, nullable=True, index=True)
    
    # Client-generated file UUID
    uuid = Column(String, unique=True, index=True, nullable=False)
    
    file_path = Column(String, nullable=False)
    file_name = Column(String, nullable=False)
    mime_type = Column(String, nullable=False)
    file_size = Column(Integer, nullable=False)
    md5 = Column(String, index=True, nullable=True)
    title = Column(String, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    log = orm_relationship("Log", back_populates="attachments")

class StickerSeries(Base):
    __tablename__ = "sticker_series"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    sort_order = Column(Integer, nullable=False, default=0)
    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_deleted = Column(Boolean, nullable=False, default=False)

class StickerConfig(Base):
    __tablename__ = "sticker_configs"

    id = Column(Integer, primary_key=True, index=True)
    series_id = Column(Integer, ForeignKey("sticker_series.id", ondelete="SET NULL"), nullable=True)
    name = Column(String, nullable=False)
    image_url = Column(String, nullable=False)
    description = Column(String, nullable=True)
    sort_order = Column(Integer, nullable=False, default=0)
    exchange_price = Column(Integer, nullable=False, default=20)
    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    is_deleted = Column(Boolean, nullable=False, default=False)


class CanvasSeries(Base):
    """
    画布系列表：对背景画布套进行大分类
    """
    __tablename__ = "canvas_series"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    sort_order = Column(Integer, nullable=False, default=0)  # 系列间的显示排序
    is_active = Column(Boolean, nullable=False, default=True)  # 启用状态
    is_deleted = Column(Boolean, nullable=False, default=False)  # 软删除
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)


class CanvasSet(Base):
    """
    画布套/商品表：商城的兑换单元（如 3001 '侏罗纪森林'）
    """
    __tablename__ = "canvas_sets"

    id = Column(Integer, primary_key=True, index=True)  # 自增主键，从 3001 起步
    series_id = Column(Integer, ForeignKey("canvas_series.id", ondelete="SET NULL"), nullable=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=True)
    sort_order = Column(Integer, nullable=False, default=0)  # 同系列内的展示排序
    exchange_price = Column(Integer, nullable=False, default=50)  # 兑换所需蛋能量
    is_active = Column(Boolean, nullable=False, default=True)
    is_deleted = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)


class CanvasInstance(Base):
    """
    画布图片实例表：保存特定比例画布裁剪后物理图片的真实信息
    """
    __tablename__ = "canvas_instances"

    id = Column(Integer, primary_key=True, index=True)  # 自增主键，从 4001 起步
    canvas_set_id = Column(Integer, ForeignKey("canvas_sets.id", ondelete="CASCADE"), nullable=False)
    aspect_ratio = Column(String, nullable=False)  # 枚举："16:9", "4:3", "1:1", "2:1"
    image_url = Column(String, nullable=False)  # 静态图片路径
    width = Column(Integer, nullable=False, default=1440)
    height = Column(Integer, nullable=False)  # 基于宽高比计算的高度
    is_active = Column(Boolean, nullable=False, default=True)
    is_deleted = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    # 联合唯一性约束，防止同套画布下重复上传相同比例的图片
    __table_args__ = (
        UniqueConstraint("canvas_set_id", "aspect_ratio", name="uq_canvas_set_ratio"),
    )


class LogCanvas(Base):
    """
    日记画布关联表：维护日记与特定背景画布实例的关系
    """
    __tablename__ = "log_canvases"

    log_uuid = Column(String, ForeignKey("logs.uuid", ondelete="CASCADE"), primary_key=True)
    canvas_instance_id = Column(Integer, ForeignKey("canvas_instances.id", ondelete="SET NULL"), nullable=True)
    canvas_aspect_ratio = Column(String, nullable=False, default="2:1")  # "16:9", "4:3", "1:1", "2:1"


class ShopItem(Base):
    """
    统一商品销售表：自增主键从 7001 起步
    统一管理手账商城的商品售价、上架与结算属性，与领域资产物理表彻底解耦
    """
    __tablename__ = "shop_items"

    id = Column(Integer, primary_key=True, index=True)  # 7001 起步
    item_type = Column(String, nullable=False, index=True)  # "STICKER" | "CANVAS_SET" (未来扩展 "FONT" 等)
    target_id = Column(Integer, nullable=False, index=True)  # 关联 sticker_configs.id 或 canvas_sets.id
    original_price = Column(Integer, nullable=False, default=20)  # 基础蛋能量售价
    sort_order = Column(Integer, nullable=False, default=0)  # 商城展示排序
    is_active = Column(Boolean, nullable=False, default=True)  # 是否上架
    is_deleted = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)


class Promotion(Base):
    """
    促销活动主表：自增主键从 5001 起步
    """
    __tablename__ = "promotions"

    id = Column(Integer, primary_key=True, index=True)  # 5001 起步
    name = Column(String, nullable=False)  # 活动名称，如 "2026儿童节手账狂欢"
    description = Column(String, nullable=True)  # 活动文案说明
    start_time = Column(DateTime, nullable=False)  # 生效开始时间 (UTC)
    end_time = Column(DateTime, nullable=False)  # 生效结束时间 (UTC)
    is_active = Column(Boolean, nullable=False, default=True)  # 启用/停用开关
    is_deleted = Column(Boolean, nullable=False, default=False)  # 软删除
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    targets = orm_relationship("PromotionTarget", back_populates="promotion", cascade="all, delete-orphan")


class PromotionTarget(Base):
    """
    促销适用目标与规则表：自增主键从 6001 起步
    """
    __tablename__ = "promotion_targets"

    id = Column(Integer, primary_key=True, index=True)  # 6001 起步
    promotion_id = Column(Integer, ForeignKey("promotions.id", ondelete="CASCADE"), nullable=False)
    
    # 作用范围: "ALL" | "ITEM_TYPE" | "SERIES" | "SHOP_ITEM"
    target_scope = Column(String, nullable=False, default="ALL")
    target_type = Column(String, nullable=True)  # "STICKER" | "CANVAS_SET"
    target_id = Column(Integer, nullable=True)  # series_id 或 shop_items.id
    
    # 优惠方式
    discount_rate = Column(Float, nullable=True)  # 折扣率（如 0.80）
    fixed_price = Column(Integer, nullable=True)  # 单品一口价（蛋能量整数）
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    promotion = orm_relationship("Promotion", back_populates="targets")


class EggEnergyTargetType(Base):
    """
    目标实体元数据维度字典表
    定义流水中的 target_id 映射到哪张物理数据表与展示属性
    """
    __tablename__ = "egg_energy_target_types"

    target_type_id = Column(Integer, primary_key=True)  # 1=商品, 2=签到, 3=日记, 4=奖品
    target_code = Column(String, unique=True, nullable=False, index=True)  # "SHOP_ITEM", "CHECK_IN", "LOG", "PRIZE"
    table_name = Column(String, nullable=False)  # "shop_items", "check_in_records", "logs", "prizes"
    pk_column = Column(String, nullable=False, default="id")  # 统一关联物理主键 "id"
    title_column = Column(String, nullable=False)  # 展示标题列名
    image_column = Column(String, nullable=True)  # 展示图片URL列名
    badge_label = Column(String, nullable=False)  # UI展示角标


class EggEnergyEventType(Base):
    """
    行为事件类型维度字典表
    定义流水发生时的业务行为、变动方向及显示名称
    """
    __tablename__ = "egg_energy_event_types"

    event_type_id = Column(Integer, primary_key=True)  # 101, 201, 301, 401...
    event_code = Column(String, unique=True, nullable=False, index=True)  # "DAILY_CHECKIN", "LOG_REWARD", "SHOP_EXCHANGE"
    target_type_id = Column(Integer, ForeignKey("egg_energy_target_types.target_type_id"), nullable=False)
    direction = Column(String, nullable=False)  # "EARN" 或 "SPEND"
    display_name = Column(String, nullable=False)  # 如 "每日敲蛋签到", "手账日记奖励", "手账商城兑换"
    icon_key = Column(String, default="default", nullable=False)  # 备用矢量图标

    target_type = orm_relationship("EggEnergyTargetType")


class CheckInRecord(Base):
    """
    每日签到历史记录表
    全量记录用户的每一次签到足迹、获得的随机奖励与暴击状态
    """
    __tablename__ = "check_in_records"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    check_in_date = Column(String(10), nullable=False)  # "YYYY-MM-DD"
    energy_reward = Column(Integer, nullable=False)  # 基础随机奖励
    streak_bonus = Column(Integer, nullable=False, default=0)  # 连签加成奖励
    is_crit = Column(Boolean, nullable=False, default=False)  # 是否触发欧皇暴击
    streak_days = Column(Integer, nullable=False, default=1)  # 截止当日连续签到天数
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    user = orm_relationship("User")

    __table_args__ = (
        UniqueConstraint("user_id", "check_in_date", name="uq_user_checkin_date"),
        Index("idx_checkin_user_date", "user_id", "check_in_date"),
    )


class CheckInConfig(Base):
    """
    签到随机算法与连签加成配置表 (Admin 可视化配置)
    """
    __tablename__ = "check_in_configs"

    id = Column(Integer, primary_key=True, index=True)
    base_min = Column(Integer, nullable=False, default=5)  # 基础日常保底能量
    base_max = Column(Integer, nullable=False, default=15)  # 基础日常最高能量
    crit_rate = Column(Float, nullable=False, default=0.15)  # 欧皇暴击概率 (15%)
    crit_min = Column(Integer, nullable=False, default=30)  # 暴击最小能量
    crit_max = Column(Integer, nullable=False, default=66)  # 暴击最大能量
    streak_enabled = Column(Boolean, nullable=False, default=True)  # 连签加成开关
    streak_rules_json = Column(Text, nullable=False, default='{"3": 5, "7": 20}')  # 连签天数: 加成值 JSON
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow, nullable=False)


class EggEnergyTransaction(Base):
    """
    蛋能量事实流水账本 (Egg Energy Transactions Ledger)
    全量记录每一笔蛋能量的获取与消耗明细，纯整型强类型关联
    """
    __tablename__ = "egg_energy_transactions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    event_type_id = Column(Integer, ForeignKey("egg_energy_event_types.event_type_id"), nullable=False)
    change_amount = Column(Integer, nullable=False)  # 变动数值 (正数获取，负数消耗)
    balance_after = Column(Integer, nullable=False)  # 变动后的瞬时余额
    target_type_id = Column(Integer, ForeignKey("egg_energy_target_types.target_type_id"), nullable=False)
    target_id = Column(Integer, nullable=False)  # 严格强类型整型外键，关联目标业务表的 id
    request_uuid = Column(String(36), unique=True, nullable=False, index=True)  # 幂等唯一键
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    user = orm_relationship("User")
    event_type = orm_relationship("EggEnergyEventType")
    target_type = orm_relationship("EggEnergyTargetType")

    __table_args__ = (
        Index("idx_energy_tx_user_created", "user_id", "created_at"),
        Index("idx_energy_tx_target", "target_type_id", "target_id"),
    )






